
spring:
  config:
    activate:
      on-profile: integration
  application:
    name: employee-api-integration

api:
  server-uri: http://localhost:8112/api/v1
  connection-timeout: 3000
  read-timeout: 3000

integration:
  server-uri: http://localhost
  path: api/v2
  connection-timeout: 3000
  read-timeout: 3000

server:
  port: 8111
  compression:
    enabled: true